### Benchmark
benchmark: 
    benchmark: "perqa"
    benchmark_dir: "./data/benchmarks/perqa"
    result_dir: "./data/results/perqa/query_generation_openai"

### ICL
openai: 
    openai_model: "gpt-4o"
    openai_organization: "<YOUR_ORG>"
    openai_project: "<YOUR_PROJECT>"
    openai_key: "<YOUR_KEY>"
    use_cache: True

### Query generation
query_generation:
    mode_options: ["openai", "instruct_model", "seq2seq"] 
    mode: "openai"
    instruction: "./prompts/instruction-sql_query_generation.txt"
    prompt: "./prompts/prompt-sql_query_generation.txt"
    icl_examples: "./prompts/icl-sql_query_generation.json"
    sql_schema: "./prompts/sql_schema.txt"
    result_path: "./data/results/perqa/query_generation_openai/query_generation_result_test.jsonl"
    sampling_params:
        n: 1
        temperature: 0.0
        max_tokens: 300
